"# NSMC 프로젝트 설정 파일" 
"" 
"# 데이터 설정" 
"data:" 
"  raw_data_path: 'data/raw/'" 
"  processed_data_path: 'data/processed/'" 
"  train_file: 'ratings_train.txt'" 
"  test_file: 'ratings_test.txt'" 
"" 
"# 모델 설정" 
"model:" 
"  random_state: 42" 
"  test_size: 0.2" 
"  target_accuracy: 0.85" 
"" 
"# 실험 설정" 
"experiment:" 
"  model_save_path: 'models/trained/'" 
"  results_save_path: 'results/'" 
"  figures_save_path: 'reports/figures/'" 
